name: core-suite-demo
version: '3.7'
services:
    ingress:
        build:
          context: .
          dockerfile: Dockerfile.nginx
        domainname: docker.local
        ports:
            - 80:80
        restart: always
        depends_on:
          - core-inventory
          - core-work


    core-inventory:
      image: ghcr.io/eed-web-application/core-inventory-system:latest
      pull_policy: always
      restart: on-failure
      environment:
        - CIS_MONGODB_URI=mongodb://cis:cis@mongodb-primary:27017/cis?authSource=cis
        - CIS_ADMIN_MONGODB_URI=mongodb://admin:admin@mongodb-primary:27017/?authSource=admin
        - WAIT_LOGGER_LEVEL=debug
        - WAIT_TIMEOUT=90
        - WAIT_HOSTS=mongodb-primary:27017
        - SPRING_PROFILES_ACTIVE=test,manage-root-user,init-demo-database
        - CIS_ROOT_AUTHENTICATION_TOKEN_JSON=[{\"name\":\"root-token-1\",\"expiration\":\"2024-12-31\"}]
      ports:
        - "8081:8080"
      depends_on:
          - mongodb-primary

    core-work:
      image: ghcr.io/eed-web-application/core-work-management:latest
      pull_policy: always
      restart: on-failure
      environment:
        - CWM_MONGODB_URI=mongodb://cwm:cwm@mongodb-primary:27017/cwm?authSource=cwm
        - CWM_ADMIN_MONGODB_URI=mongodb://admin:admin@mongodb-primary:27017/?authSource=admin
        - WAIT_LOGGER_LEVEL=debug
        - WAIT_TIMEOUT=90
        - WAIT_HOSTS=mongodb-primary:27017
        - SPRING_PROFILES_ACTIVE=test,manage-root-user,init-demo-database
        - CWM_ROOT_AUTHENTICATION_TOKEN_JSON=[{\"name\":\"root-token-1\",\"expiration\":\"2024-12-31\"}]
      ports:
        - "8082:8080"
      depends_on:
        - mongodb-primary

    mongodb-primary:
      image: ghcr.io/zcube/bitnami-compat/mongodb:6.0.5
      restart: on-failure
      environment:
        - MONGODB_ROOT_USER=admin
        - MONGODB_ROOT_PASSWORD=admin
        - BITNAMI_DEBUG=true
        - MONGODB_REPLICA_SET_MODE=primary
        - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
        - MONGODB_REPLICA_SET_KEY=replicasetkey123
      ports:
        - "27017:27017"